# slogan: chat next
# port: 3000

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - SERVICE_FQDN_WEB_3000
      - test=$TEST

    healthcheck:
      test: ["CMD", "curl", "-f", "http://127.0.0.1:3000"]
      interval: 30s
      timeout: 10s
      retries: 5

